name: Simple CI job

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: |
          echo "Current date: $(date +"%Y-%m-%d")"
          echo "Current time: $(date +"%H:%M:%S")"